
spring:
  ###################### mysql ###########################
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xx:3306/jian3?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: xx
    password: xx
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=3s
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: ${package}.db.model
  config-location: classpath:mybatis.xml

mapper:
  mappers:
  - ${package}.db.config.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 30001
test:
  text: 3
